@startuml
title List Of Overdue Lendings
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : List overdue lendings
LMS --> HTTP_Client : 200 - List of overdue lendings

@enduml