@startuml
rectangle "Lending" <<Container (C4)>> #skyblue {
    rectangle "Lending Backend" as lending_backend #skyblue
    database "H2 Database" as lending_db
}
lending_backend -[#black,plain]-(0 lending_db : JPA
@enduml