@startuml
title View Book Details Given ISBN
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : View book details
LMS --> HTTP_Client : 200 - book details or 404 - not found

@enduml