@startuml
title Top 5 Books Lent
actor "HTTP Client" as client
participant ":Books" as Books

client -> Books: 1: GET /api/books/top/lent
activate Books
Books -> client: 2: 200 OK - List of Top 5 Books Lent
deactivate Books
@enduml