@startuml
title Top 5 Authors
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : Get top 5 authors
LMS --> HTTP_Client : 200 - list of top 5 authors

@enduml