@startuml
title Top 5 Authors
actor "HTTP Client" as client
participant ":Books" as Books

client -> Books: 1: GET /api/authors/top
activate Books
Books -> client: 2: 200 OK - List of Top 5 Authors
deactivate Books
@enduml