@startuml
title Register Book
actor "HTTP Client" as client
participant ":Books" as Books

client -> Books: 1: PUT /api/books/{ISBN}
activate Books
alt if exception is returned
  Books -> client: 2: 409 Conflict - Book already exists
else
  Books -> client: 3: 201 - Registered book
end
deactivate Books
@enduml