@startuml
title Register Book With Cover Photo
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : Register new book with cover photo
LMS --> HTTP_Client : 201 - ok or 409 - conflict

@enduml