@startuml
title Register Author With Optional Photo
actor "HTTP Client" as client
participant ":Books" as Books

client -> Books: 1: PUT /api/authors/{authorNr}
activate Books
alt if exception is returned
  Books -> client: 2: 409 Conflict - Author already exits

else
  Books -> client: 3: 201 - Author registered with optional photo
end
deactivate Books
@enduml