@startuml
title Search Books By Genre
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : Search books by genre
LMS --> HTTP_Client : 200 - books or 404 - not found

@enduml