@startuml
title Register Author With Optional Photo
actor HTTP_Client as "HTTP Client"
participant LMS as ":LMS"
autoactivate on

HTTP_Client -> LMS : Register new author with optional photo
LMS --> HTTP_Client : 201 - ok or 409 - conflict

@enduml